# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cumul', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=25)),
                ('libelle', models.TextField()),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ecriture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'entrée")),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commentaires', models.TextField(null=True)),
                ('validee', models.BooleanField(default=False)),
                ('mensuelle', models.BooleanField(default=False)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Cause')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Compte')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouv', models.CharField(max_length=2)),
                ('cumul', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Compte')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cumul', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Compte')),
            ],
        ),
        migrations.AddField(
            model_name='ecriture',
            name='mouv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Mouvement'),
        ),
        migrations.AddField(
            model_name='ecriture',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Poste'),
        ),
        migrations.AddField(
            model_name='cause',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Compte'),
        ),
    ]
