# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_mouvement_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecriture',
            name='mensuelle',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='ecriture',
            name='validee',
            field=models.CharField(max_length=1),
        ),
    ]
